// app/layout.tsx
"use client";  // 添加这一行来标记文件为客户端组件

import { Geist, Geist_Mono } from "next/font/google";
import useTheme from './theme';  // 导入刚才创建的 useTheme
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useTheme();  // 在布局中调用 theme 切换逻辑

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
